RunDiary/Controllers/AddRunController.cs
//using Microsoft.Owin;
using RunDiary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace RunDiary.Controllers
{
    public class AddRunController : ApiController
       

    {
        private RDRepository repo = new RDRepository();

        // GET: api/AddRun
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/AddRun/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/AddRun
        public void Post(Run newRun)
        {
            repo.AddRun(newRun);
        }


        // PUT: api/AddRun/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/AddRun/5
        public void Delete(int id)
        {
            //var query = from run in _context.Runs select run where runID == id;
            //Run runToDelete = find the run with matching id
           // repo.DeleteRun(runToDelete);
        }
    }
}

RunDiary/Controllers/RunDiaryController.cs
using RunDiary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
//using System.Web.Http;
using System.Web;

//using System.Web.Http;
using System.Web.Mvc;

namespace RunDiary.Controllers
{
    public class RunDiaryController : Controller
    {
        public RDRepository Repo { get; set; }

        public RunDiaryController() : base()
        {
            Repo = new RDRepository();
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Calendar()
        {
            List<Run> my_runs = Repo.GetAllRuns();
            return View(my_runs);
        }

        public ActionResult AddRun()
        {
            Run model = new Run();
            return View(model);
        }

        [HttpPost]
        public ActionResult Calendar(Run newRun)
        {
            
           Repo.AddRun(newRun);
            List<Run> my_runs = Repo.GetAllRuns();
            return View(my_runs);
        }

        public ActionResult EditRun(int id)
        {
            var run = Repo.GetRun(id);
            return View(run);
        }

        [HttpPut]
        public ActionResult EditRun(int id, Run newRun)
        {
            var run = Repo.GetRun(id);
            Repo.DeleteRun(run);
            return View();
        }

        public ActionResult DeleteRun(int id)
        {
            var run = Repo.GetRun(id);
            return View(run);
        }

        //[HttpDelete]
        public ActionResult RunDeleted (Run run)
        {
            //var run = Repo.GetRun(id);
            Repo.DeleteRun(run);
            return View();
        }


    }
}

RunDiary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
@Html.Partial("_Nav")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RunDiary/Views/Shared/_Nav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Run Diary", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*@if (Request.IsAuthenticated)
                    {*@

                <li>@Html.ActionLink("Calendar View", "Calendar", "RunDiary")</li>
                <li>@Html.ActionLink("Add Run", "AddRun", "RunDiary")</li>
                <li>@Html.ActionLink("Welcome Page", "Index", "RunDiary")</li>
                @*
                            }
                            else
                           {
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    }*@
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

RunDiary/Views/Shared/_RunDiary.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/datepicker.css")
    @Styles.Render("~/fullcalendar-2.5.0/fullcalendar.css")


</head>
<body>
    @Html.Partial("_Nav")
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-ui-1.11.4.js")
    @Scripts.Render("~/Scripts/main.js")
    @Scripts.Render("~/fullcalendar-2.5.0/lib/moment.min.js")
    @Scripts.Render("~/fullcalendar-2.5.0/fullcalendar.js")
    @RenderSection("scripts", required: false)


</body>
</html>